# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 50
  min_messages: warning

development:
  database: miszczsenk
  username:
  password:
  <<: *common

test:
  database: miszczsenk_test
  <<: *common
